config/routes.rb
Rails.application.routes.draw do
  resources :pictures

  root 'pictures#index'
  match 'auth/:provider/callback', to: 'sessions#create', via: [:get, :post]
  match 'auth/failure', to: redirect('/'), via: [:get, :post]
  match 'signout', to: 'sessions#destroy', as: 'signout', via: [:get, :post]

end

app/models/picture.rb
class Picture < ActiveRecord::Base
end

app/models/user.rb
# class User < ActiveRecord::Base
#  def self.from_omniauth(auth)
#     where(auth.slice(:provider, :uid)).first_or_initialize.tap do |user|
#       user.provider = auth.provider
#       user.uid = auth.uid
#       user.name = auth.info.name
#       user.oauth_token = auth.credentials.token
#       user.oauth_expires_at = Time.at(auth.credentials.expires_at)
#       user.save!
#     end
#   end
# end

class User < ActiveRecord::Base
 def self.from_omniauth(auth)
  where(provider: auth.provider, uid: auth.uid).first_or_create do |user|
	    user.provider = auth.provider 
	    user.uid      = auth.uid
	    user.name     = auth.info.name
	    user.oauth_token = auth.credentials.token
	    user.oauth_expires_at = Time.at(auth.credentials.expires_at)
	    user.save
    	end
  end
end

app/controllers/application_controller.rb
# class ApplicationController < ActionController::Base
#   # Prevent CSRF attacks by raising an exception.
#   # For APIs, you may want to use :null_session instead.
#   protect_from_forgery with: :exception

#   private
#   def current_user
#     @current_user ||= User.find(session[:user_id]) if session[:user_id]
#   end
#   helper_method :current_user
# end

class ApplicationController < ActionController::Base
  protect_from_forgery

  private
  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end
  helper_method :current_user
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # GET /pictures/1/edit
  def edit
  end

  # POST /pictures
  # POST /pictures.json
  def create
    @picture = Picture.new(picture_params)

    respond_to do |format|
      if @picture.save
        format.html { redirect_to pictures_path, notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pictures/1
  # PATCH/PUT /pictures/1.json
  def update
    respond_to do |format|
      if @picture.update(picture_params)
        format.html { redirect_to @picture, notice: 'Picture was successfully updated.' }
        format.json { render :show, status: :ok, location: @picture }
      else
        format.html { render :edit }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:title, :url)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.from_omniauth(env["omniauth.auth"])
    session[:user_id] = user.id
    redirect_to root_url
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_url
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Wynstagram</title>
  <!-- Bootstrap CDN link -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.1/css/bootstrap.min.css">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <!-- Google Fonts link --> 
  <link href='https://fonts.googleapis.com/css?family=Montserrat' rel='stylesheet' type='text/css'>
  <!-- Font Awesome -->
  <link href="//maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

<!-- Facebook Login -->

app/views/pictures/_facebook.html.erb
  <div id="user-widget">
    <% if current_user %>
    Welcome <strong><%= current_user.name %></strong>!
    <%= link_to "Sign out", signout_path, id: "sign_out" %>
    <% else %>
    <div id="login">
      <%= link_to "/auth/facebook", id: "sign_in" do %>
        <i class="fa fa-facebook-square fa-2x"></i>
      <% end %>
    </div>
    <% end %>
  </div>

app/views/pictures/_form.html.erb
<%= form_for(@picture) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label "Title" %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label "URL" %><br>
    <%= f.text_field :url %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<div id="header">

  <a href="https://quiet-temple-2033.herokuapp.com/" class="home_link"><h1 id="headline">Wynstagram</h1><i class="fa fa-paint-brush fa-3x"></i></a>
</div>


<br>
<br>
<br>
<br>
<br>

<div class="text-center new_box">

  <h1>Edit</h1>



  <%= render 'form' %>

  <%= link_to 'Show', @picture %> |
  <%= link_to 'Back', pictures_path %>

</div>

app/views/pictures/index.html.erb
<div id="header">

  <a href="https://quiet-temple-2033.herokuapp.com/" class="home_link"><h1 id="headline">Wynstagram</h1><i class="fa fa-paint-brush fa-3x"></i></a>
  <div class="new_button"><%= link_to '', new_picture_path, class:"fa fa-plus-square fa-2x" %>
  <!-- Facebook Login -->
  <%= render 'facebook' %>
  </div>
</div>
<br>

<div id="container">
  <% @pictures.each do |picture| %>
  <div class="item">
     <%= link_to picture.url, data: { lightbox:"photogur" } do %>
            <%= image_tag picture.url, class:"size-#{rand(3) + 1}" %>
              <% end %>
      
      <div class="options">
      <h3><%= picture.title %></h3>
      <!-- <%= link_to 'Show', picture, class:"fa fa-search" %> -->
      <%= link_to '', edit_picture_path(picture), class:"fa fa-pencil fa-2x" %>
      <%= link_to '', picture, method: :delete, data: { confirm: 'Are you sure?' }, class:"fa fa-times fa-2x" %>
      </div>
    </div>
  <% end %>
</div>

  <br>

 <footer id="footer">Copyright&copy; | Wynfinite Loop | 2014</footer>

app/views/pictures/new.html.erb
<div id="header">

  <a href="https://quiet-temple-2033.herokuapp.com/" class="home_link"><h1 id="headline">Wynstagram</h1><i class="fa fa-paint-brush fa-3x"></i></a>
</div>


<br>
<br>
<br>
<br>
<br>

<div class="text-center new_box">

  <h1>New picture</h1>

  <%= render 'form' %>

<br>
  <%= link_to '', pictures_path, class:"fa fa-caret-square-o-left fa-2x" %>
</div>

app/views/pictures/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @picture.title %>
</p>

<p>
  <%= image_tag @picture.url %>
</p>

<%= link_to 'Edit', edit_picture_path(@picture) %> |
<%= link_to 'Back', pictures_path %>